title: "The Knutt Pipeline"
remote_theme: pmarsceill/just-the-docs
#Prefer light for now
color_scheme: "light"
search_enabled: false
# No logo (yet)
# logo: "/assets/images/just-the-docs.png"
heading_anchors: true
aux_links:
  "Check out the repos on Github":
    - "//github.com/KnuttPipeline"
  "Started at the UAS Emden/Leer":
    - "//www.hs-emden-leer.de/fachbereiche/technik/forschung-institute/umweltmikrobiologie/"
#logo: "/assets/images/logo.png"
# footer_content: "HTML code footer here"